### ISSUE TITLE
senDownSearch 

### ISSUE THREAD

**Issue by jaimebayes** [spatialstatisticsupna/RGISTools#5]
Hi, 

I am trying to run this code snippet with using senDownSearch function from RGIStools, but it throws back an error. I am just following the tutorial steps. The username and password are working fine, they was tested previously. 
Any help would be appreciated. Thanks in advance, JL

`senDownSearch(startDate = as.Date("2018210", "%Y%j"),
              endDate = as.Date("2018218", "%Y%j"),
              platform = "Sentinel-2",
              extent = ex.navarre,
              product = "S2MSI1C",
              pathrow = c("R094"),
              username = "xxxxx",
              password = "*****",
              AppRoot = wdir)`

6 tiles found! Starting the download process...
Error in senDownload(searchres = senURL, username = username, password = password,  : 
  **A response from sentinel search function is needed.**

**Comment by unai-perez** [comment]
fixed!
