### ISSUE TITLE
upcoming stars release breaks RGISTools, through tmap

### ISSUE THREAD

**Issue by edzer** [spatialstatisticsupna/RGISTools#7]
@mtennekes
I submnitted stars 0.5-0 to CRAN, which causes a reverse depency error in RGISTools (see [here](https://win-builder.r-project.org/incoming_pretest/stars_0.5-0_20210116_233311/reverseDependencies/summary.txt)):
```
Changes to worse in reverse depends:

Package: RGISTools
Check: examples
New result: ERROR
  Running examples in â€˜RGISTools-Ex.Râ€™ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: genCompositions
  > ### Title: Create image compositions from a time series of satellite images
  > ### Aliases: genCompositions
  > 
  > ### ** Examples
  > 
  > # loading NDVI images of Navarre
  > data("ex.ndvi.navarre")
  > # Ploting the images: clouds are found
  > genPlotGIS(ex.ndvi.navarre)
  Warning: col specification in tm_raster is ignored, since stars object contains a 3rd dimension, where its values are used to create facets
  Error in dim.stars(x) : length(d) == length(dim(x[[1]])) is not TRUE
  Calls: <Anonymous> ... do.call -> plot_1 -> nrow -> dim -> dim.stars -> stopifnot
  Execution halted
```

The cause for this is in tmap/tmaptools, and if I update tmap and tmaptools to their github versions this error goes away. So I can see two options for this:

* change RGISTools (e.g. out-comment all calls to `genPlotGIS` from the examples, and add a warning when using it that tmap/tmaptools should have a minimum version and be installed from github), or
*  update tmap and/or tmaptools on CRAN

Martijn, when do you have in mind you could submit new tmap/tmaptools, is this waiting for a CRAN release of stars?

**Comment by mtennekes** [comment]
@edzer Yes, I can submit tmap/tmaptools to CRAN today. I'll let you know asap.

**Comment by edzer** [comment]
Great, that would solve this issue. stars 0.5-0 is now on CRAN.

**Comment by mtennekes** [comment]
tmap 3.3 also on its way to CRAN
